version: '2'
services:
  demo_svc:
    image: 725827686899.dkr.ecr.us-west-2.amazonaws.com/arun/docker/demo_svc:latest
    mem_limit: 134217728
    expose:
      - 9000
    environment:
      - PORT=9000
    ports:
      - "9000:9000"
