version: '2'
services:
  web:
    build: ./demo_ui
    image: demo_ui:latest
    links:
      - demo_svc
    environment:
      - SERVICE_URI_HOST=demo_svc
      - SERVICE_URI_PORT=9000
    expose:
      - 8080
    ports:
      - "8080:8080"
  demo_svc:
    build: ./demo_svc
    image: demo_svc:latest
    expose:
      - 9000
    environment:
      - PORT=9000
